name: Build, test and lint job-visualizer

on:
  push:
    branches: 
        - "main"
        - "github-actions"
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libgl1-mesa-dev libx11-dev libxrandr-dev

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Download Dependencies
      run: go mod tidy

    - name: Build
      working-directory: cmd/app
      run: go build -o job-visualizer

    # - name: Test
    #   run: go test -v ./...

    # - name: Install golangci-lint
    #   run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    # - name: Run golangci-lint
    #   run: golangci-lint run